function [fitresult, gof] = rswe_besselfit_axial(z_axis, z_vector)
%CREATEFITS(Y_V2,R_CC2,I_CC2)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : y_v2
%      Y Output: R_cc2
%  Data for 'untitled fit 2' fit:
%      X Input : y_v2
%      Y Output: I_cc2
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Jun-2020 19:37:45

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( z_axis, z_vector );
% Set up fittype and options.
ft = fittype( '3*(((sin(k*x)./((k*x).^2))-cos(k*x)./(k*x))./(k*x))', 'independent', 'x', 'dependent', 'y' );
% excludedPoints = ( yData>=1);
excludedPoints = ((xData <= -0.002) | (xData > 0.002)| yData>=1);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = 500;
opts.StartPoint = 0.8002804688888;
opts.Exclude = excludedPoints;
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

end




